# Generated by Django 3.0.4 on 2020-03-22 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid19helplineinfoapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocalHelpInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=300)),
                ('area', models.CharField(blank=True, max_length=300)),
                ('city', models.CharField(blank=True, max_length=30)),
                ('country', models.CharField(blank=True, max_length=30)),
                ('zip_code', models.IntegerField(blank=True, default=0, null=True)),
                ('phone_number', models.CharField(max_length=20)),
                ('helpline_phonenumber', models.CharField(blank=True, max_length=300)),
                ('helpline_email', models.CharField(blank=True, max_length=300)),
                ('helpline_centre_address', models.CharField(blank=True, max_length=300)),
                ('howto_get_there', models.CharField(blank=True, max_length=10240)),
                ('other_instructions', models.CharField(blank=True, max_length=10240)),
                ('map_location_url', models.CharField(blank=True, max_length=10240)),
                ('info_verified', models.BooleanField()),
                ('info_source', models.CharField(blank=True, max_length=10240)),
            ],
        ),
    ]
