# Generated by Django 3.0.4 on 2020-03-22 07:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('covid19helplineinfoapp', '0002_localhelpinfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='localhelpinfo',
            name='info_verified',
        ),
        migrations.RemoveField(
            model_name='localhelpinfo',
            name='phone_number',
        ),
        migrations.AlterField(
            model_name='localhelpinfo',
            name='city',
            field=models.CharField(blank=True, max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='localhelpinfo',
            name='country',
            field=models.CharField(blank=True, max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='localhelpinfo',
            name='helpline_centre_address',
            field=models.TextField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='localhelpinfo',
            name='howto_get_there',
            field=models.TextField(blank=True, max_length=10240),
        ),
        migrations.AlterField(
            model_name='localhelpinfo',
            name='info_source',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='localhelpinfo',
            name='map_location_url',
            field=models.TextField(blank=True, max_length=10240),
        ),
        migrations.AlterField(
            model_name='localhelpinfo',
            name='other_instructions',
            field=models.TextField(blank=True, max_length=10240),
        ),
        migrations.CreateModel(
            name='HelpInfoUpvote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upvote_ipaddress', models.CharField(max_length=30, unique=True)),
                ('belongs_to_helpinfo', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='covid19helplineinfoapp.LocalHelpInfo')),
            ],
        ),
    ]
