# Generated by Django 3.0.4 on 2020-03-22 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid19helplineinfoapp', '0006_remove_localhelpinfo_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='localhelpinfo',
            name='area',
        ),
        migrations.AddField(
            model_name='profile',
            name='state',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
