# Generated by Django 3.0.4 on 2020-03-22 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid19helplineinfoapp', '0008_auto_20200322_1605'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_cases', models.IntegerField(blank=True, default=0, null=True)),
                ('total_recovered', models.IntegerField(blank=True, default=0, null=True)),
                ('total_death', models.IntegerField(blank=True, default=0, null=True)),
                ('total_ongoing', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news', models.TextField(blank=True, max_length=10240)),
                ('link', models.TextField(blank=True, max_length=10240)),
            ],
        ),
    ]
