# Generated by Django 2.2 on 2020-03-22 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid19helplineinfoapp', '0009_dashboard_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboard',
            name='important_message',
            field=models.TextField(blank=True, max_length=10240),
        ),
    ]
