# Generated by Django 3.0.4 on 2020-03-27 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid19helplineinfoapp', '0013_auto_20200326_1850'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='help_seeker',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='volunteer',
            field=models.BooleanField(default=False),
        ),
    ]
