# Generated by Django 3.0.4 on 2020-03-27 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid19helplineinfoapp', '0014_auto_20200327_0530'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='help_text',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='lat',
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='profile',
            name='lng',
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=10),
        ),
    ]
