# Generated by Django 3.0.4 on 2020-03-27 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('covid19helplineinfoapp', '0015_auto_20200327_0539'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='help_seeker',
            new_name='seeking_help',
        ),
    ]
